[2023-05-11 19:54:36] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备. 
[2023-05-11 19:54:44] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-05-11 19:54:44] [WARNING]: 请选择提交滑块ticket方式: 
[2023-05-11 19:54:44] [WARNING]: 1. 自动提交 
[2023-05-11 19:54:44] [WARNING]: 2. 手动抓取提交 
[2023-05-11 19:54:44] [WARNING]: 请输入(1 - 2)： 
[2023-05-11 19:54:47] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=thrQX34m&style=simple&aid=16&uin=3470944166&sid=249113898762688391&cap_cd=3CUoAmace_R6jWFKk9Keet3219-9zET7cKjTulqoNKxhDnlW8zZw0w**&clientype=1&apptype=2  
[2023-05-11 19:55:00] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-05-11 19:55:00] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-05-11 19:55:00] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
[2023-05-11 19:56:21] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-05-11 19:56:21] [WARNING]: 请选择提交滑块ticket方式: 
[2023-05-11 19:56:21] [WARNING]: 1. 自动提交 
[2023-05-11 19:56:21] [WARNING]: 2. 手动抓取提交 
[2023-05-11 19:56:21] [WARNING]: 请输入(1 - 2)： 
[2023-05-11 19:56:23] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=fPRqpHqh&style=simple&aid=16&uin=1870465352&sid=4912619127113045992&cap_cd=w6pBPtBvN317XAbM3II7bUuiwP5PaFUtA_CXo8cCFfHUdmFbbcIu6A**&clientype=1&apptype=2  
[2023-05-11 19:56:36] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-05-11 19:56:36] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-05-11 19:56:36] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
[2023-05-11 19:58:14] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-05-11 19:58:14] [WARNING]: 请选择提交滑块ticket方式: 
[2023-05-11 19:58:14] [WARNING]: 1. 自动提交 
[2023-05-11 19:58:14] [WARNING]: 2. 手动抓取提交 
[2023-05-11 19:58:14] [WARNING]: 请输入(1 - 2)： 
[2023-05-11 19:58:14] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=d1hsElVk&style=simple&aid=16&uin=1870465352&sid=8449916091443763289&cap_cd=w0euPFrjCBC_Fe9PiVIVf8OF5ixdVMiCUzQ0ef9eT3MOyP0GBRS3gQ**&clientype=1&apptype=2  
[2023-05-11 19:58:35] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-05-11 19:58:35] [WARNING]: 请选择提交滑块ticket方式: 
[2023-05-11 19:58:35] [WARNING]: 1. 自动提交 
[2023-05-11 19:58:35] [WARNING]: 2. 手动抓取提交 
[2023-05-11 19:58:35] [WARNING]: 请输入(1 - 2)： 
[2023-05-11 19:58:40] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=KpEuJRsE&style=simple&aid=16&uin=1870465352&sid=3644205196002515054&cap_cd=O5E4AOAPu5qWNFNbPq6X3z7yVFjrbN-Q-IczvVQdpvYHty4AVQNoYQ**&clientype=1&apptype=2  
[2023-05-11 19:58:55] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-05-11 19:58:55] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-05-11 19:58:55] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
[2023-05-11 22:24:30] [WARNING]: 登录失败: 帐号或密码错误，请重新输入。 Code: 1 
[2023-05-11 22:26:08] [WARNING]: 登录失败: 请使用手Q扫描二维码或短信登录。 Code: 238 
[2023-05-11 22:26:20] [WARNING]: 账号密码未配置, 将使用二维码登录. 
[2023-05-11 22:26:20] [WARNING]: 将在 5秒 后继续. 
[2023-05-11 22:26:46] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-05-11 22:26:46] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:26:46] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:26:46] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:27:55] [WARNING]: 当前协议不支持二维码登录, 请配置账号密码登录. 
[2023-05-11 22:28:12] [WARNING]: 恢复会话失败: exchange_emp failed: 16 , 尝试使用正常流程登录. 
[2023-05-11 22:28:14] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-05-11 22:28:14] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-05-11 22:28:14] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
[2023-05-11 22:28:30] [WARNING]: 账号密码未配置, 将使用二维码登录. 
[2023-05-11 22:28:30] [WARNING]: 将在 5秒 后继续. 
[2023-05-11 22:29:11] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-05-11 22:29:12] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:29:14] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:29:14] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10004 
[2023-05-11 22:30:38] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-05-11 22:30:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:30:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:30:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:30:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:31:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:31:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:31:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:31:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:31:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:31:15] [WARNING]: 已开启Debug模式. 
[2023-05-11 22:31:20] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-05-11 22:31:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:31:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:31:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:31:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:31:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:31:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:31:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:31:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:31:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:31:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:32:00] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815487,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":27,"packet_sent":18,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:32:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:32:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:32:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:32:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:32:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:32:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:32:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:32:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:32:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:32:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:32:32] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815520,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":29,"packet_sent":19,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:32:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:32:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:32:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:32:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:32:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:32:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:32:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:32:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:32:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:33:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:33:05] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815552,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":30,"packet_sent":20,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:33:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:33:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:33:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:33:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:33:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:33:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:33:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:33:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:33:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:33:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:33:37] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815585,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":31,"packet_sent":21,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:33:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:33:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:33:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:33:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:33:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:33:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:33:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:34:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:34:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:34:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:34:09] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815617,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":32,"packet_sent":22,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:34:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:34:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:34:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:34:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:34:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:34:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:34:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:34:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:34:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:34:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:34:42] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815649,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":23,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:34:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:34:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:34:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:34:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:34:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:34:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:35:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:35:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:35:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:35:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:35:14] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815682,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":34,"packet_sent":24,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:35:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:35:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:35:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:35:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:35:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:35:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:35:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:35:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:35:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:35:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:35:47] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815714,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":36,"packet_sent":26,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:35:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:35:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:35:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:35:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:36:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:36:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:36:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:36:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:36:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:36:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:36:19] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815747,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":37,"packet_sent":27,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:36:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:36:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:36:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:36:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:36:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:36:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:36:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:36:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:36:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:36:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:36:52] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815779,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":38,"packet_sent":28,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:36:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:36:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:37:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:37:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:37:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:37:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:37:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:37:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:37:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:37:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:37:24] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815812,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":30,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:37:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:37:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:37:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:37:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:37:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:37:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:37:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:37:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:37:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:37:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:37:57] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815844,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":41,"packet_sent":31,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:37:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:38:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:38:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:38:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:38:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:38:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:38:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:38:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:38:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:38:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:38:29] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815877,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":42,"packet_sent":32,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:38:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:38:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:38:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:38:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:38:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:38:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:38:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:38:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:38:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:38:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:39:02] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815909,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":34,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:39:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:39:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:39:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:39:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:39:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:39:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:39:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:39:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:39:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:39:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:39:34] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815942,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":35,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:39:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:39:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:39:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:39:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:39:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:39:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:39:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:39:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:40:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:40:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:40:07] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683815974,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":36,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:40:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:40:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:40:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:40:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:40:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:40:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:40:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:40:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:40:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:45:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:45:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:45:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:45:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:45:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:45:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:45:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:45:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:45:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:45:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:45:35] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816302,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":61,"packet_sent":48,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:45:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:45:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:45:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:45:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:45:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:45:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:45:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:45:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:46:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:46:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:46:07] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816335,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":63,"packet_sent":50,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:46:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:46:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:46:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:46:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:46:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:46:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:46:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:46:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:46:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:46:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:46:39] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816367,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":64,"packet_sent":51,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:46:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:46:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:46:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:46:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:46:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:46:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:46:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:47:02] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:47:05] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:47:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:47:11] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816399,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":65,"packet_sent":52,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:47:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:47:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:47:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:47:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:47:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:47:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:47:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:47:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:47:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:47:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:47:44] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816431,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":66,"packet_sent":53,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:47:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:47:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:47:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:47:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:47:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:48:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:48:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:48:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:48:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:48:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:48:16] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816464,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":67,"packet_sent":54,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:48:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:48:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:48:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:48:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:48:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:48:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:48:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:48:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:48:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:48:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:48:49] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816496,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":68,"packet_sent":55,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:48:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:48:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:48:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:49:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:49:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:49:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:49:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
[2023-05-11 22:49:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 8 次重试 
[2023-05-11 22:49:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 9 次重试 
[2023-05-11 22:49:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 10 次重试 
[2023-05-11 22:49:21] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1683816529,"self_id":3470944166,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":56,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}},"interval":5000}
 到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上限 
[2023-05-11 22:49:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-05-11 22:49:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-05-11 22:49:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-05-11 22:49:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 4 次重试 
[2023-05-11 22:49:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 5 次重试 
[2023-05-11 22:49:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 6 次重试 
[2023-05-11 22:49:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:9928/ 失败: Post "http://127.0.0.1:9928/": dial tcp 127.0.0.1:9928: connectex: No connection could be made because the target machine actively refused it. 将进行第 7 次重试 
